# API Configuration, you can get a FREE gemini api key from https://aistudio.google.com/app/apikey
gemini_api_key: "your-api-key-here"

# how many browsers to open at the same time (keep 1 if you enable router reboot)
concurrent_tasks: 1

# Router Configuration for IP rotation via router reboot
router:
  enabled: false  # Enable/disable router reboot functionality
  ip: ""
  username: ""
  password: ""
  reboot_command: "" 

gemini_model_name: "gemini-2.0-flash-exp" # the gemini AI model to solve the captcha (visual or audio)
